"""Database creation

Revision ID: 3df58b5189a1
Revises: 
Create Date: 2023-06-05 18:47:15.351917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3df58b5189a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
